/**
 * Seed MCQ pool used by the local-first quiz catalog while Firestore data
 * is still being populated. Chapter ids match `public/content/chapters/` slugs.
 *
 * Lovable = visual generation · Cursor = engineering · GitHub = source of truth
 */

import type { McqDoc } from "@/integrations/firebase/types";

export const SEED_MCQS: McqDoc[] = [
  {
    id: "math_real_q1",
    subjectId: "math",
    chapterId: "real-numbers",
    question: "Which of these is an irrational number?",
    options: ["0.25", "√2", "3/4", "−5"],
    correctIndex: 1,
    explanation: "√2 cannot be written as p/q with integers p, q (q ≠ 0).",
    topic: "Real Numbers",
    difficulty: "Easy",
  },
  {
    id: "math_real_q2",
    subjectId: "math",
    chapterId: "real-numbers",
    question: "HCF(96, 404) = ?",
    options: ["2", "4", "8", "12"],
    correctIndex: 1,
    explanation: "404 = 4·101, 96 = 32·3 → HCF is 4.",
    topic: "Real Numbers",
    difficulty: "Medium",
  },
  {
    id: "math_quad_q1",
    subjectId: "math",
    chapterId: "quadratic-equations",
    question: "Discriminant of x² − 4x + 4 is:",
    options: ["0", "4", "−4", "16"],
    correctIndex: 0,
    explanation: "b² − 4ac = 16 − 16 = 0, so equal real roots.",
    topic: "Quadratic Equations",
    difficulty: "Medium",
  },
  {
    id: "math_quad_q2",
    subjectId: "math",
    chapterId: "quadratic-equations",
    question: "Roots of x² − 5x + 6 are:",
    options: ["1, 6", "2, 3", "−2, −3", "−1, −6"],
    correctIndex: 1,
    explanation: "Factor: (x−2)(x−3) = 0.",
    topic: "Quadratic Equations",
    difficulty: "Easy",
  },
  {
    id: "sci_light_q1",
    subjectId: "science",
    chapterId: "light-reflection-and-refraction",
    question: "A concave mirror always forms a real image when the object is:",
    options: [
      "Between pole and focus",
      "At focus",
      "Beyond focus",
      "Behind the mirror",
    ],
    correctIndex: 2,
    explanation: "Objects beyond F produce real, inverted images.",
    topic: "Light - Reflection and Refraction",
    difficulty: "Medium",
  },
  {
    id: "sci_light_q2",
    subjectId: "science",
    chapterId: "light-reflection-and-refraction",
    question: "SI unit of power of a lens is:",
    options: ["metre", "dioptre", "watt", "lumen"],
    correctIndex: 1,
    explanation: "Power P = 1/f (in metres); unit is the dioptre (D).",
    topic: "Light - Reflection and Refraction",
    difficulty: "Easy",
  },
  {
    id: "sci_elec_q1",
    subjectId: "science",
    chapterId: "electricity",
    question: "Ohm's law relates:",
    options: [
      "V, I and R",
      "Power and time",
      "Charge and current",
      "Mass and energy",
    ],
    correctIndex: 0,
    explanation: "V = IR (at constant temperature).",
    topic: "Electricity",
    difficulty: "Easy",
  },
  {
    id: "sci_elec_q2",
    subjectId: "science",
    chapterId: "electricity",
    question: "Resistors 2Ω and 3Ω in series carry 1A. Voltage across them:",
    options: ["1V", "3V", "5V", "6V"],
    correctIndex: 2,
    explanation: "Total R = 5Ω, V = IR = 5V.",
    topic: "Electricity",
    difficulty: "Medium",
  },
  {
    id: "soc_banking_q1",
    subjectId: "social",
    chapterId: "chapter_01_banking_transactions",
    question: "Demand deposits are accepted as a means of payment because:",
    options: [
      "They earn interest",
      "They are issued by RBI",
      "They can be transferred via cheque",
      "They are physical currency",
    ],
    correctIndex: 2,
    explanation: "Cheques allow demand deposits to settle payments.",
    topic: "Banking Transactions",
    difficulty: "Medium",
  },
  {
    id: "soc_banking_q2",
    subjectId: "social",
    chapterId: "chapter_01_banking_transactions",
    question: "Formal sources of credit in India are supervised by:",
    options: ["SEBI", "RBI", "NITI Aayog", "Finance Commission"],
    correctIndex: 1,
    explanation: "The RBI regulates banks and cooperative societies.",
    topic: "Banking Transactions",
    difficulty: "Easy",
  },
];
