import type {
  LibraryCategoryDoc,
  LibraryResourceDoc,
} from "@/integrations/firebase/types";

/**
 * Default categories rendered by /resources. Seed-once via the admin
 * import page; later admin edits override these.
 */
export const DEFAULT_LIBRARY_CATEGORIES: LibraryCategoryDoc[] = [
  {
    id: "textbook",
    label: "Textbooks",
    labelKn: "ಪಠ್ಯಪುಸ್ತಕಗಳು",
    description: "Karnataka KTBS and NCERT textbooks",
    icon: "BookOpen",
    order: 1,
  },
  {
    id: "pyq",
    label: "Previous Year Papers",
    labelKn: "ಹಿಂದಿನ ವರ್ಷದ ಪ್ರಶ್ನೆಪತ್ರಿಕೆಗಳು",
    description: "Board papers and model question papers",
    icon: "GraduationCap",
    order: 2,
  },
  {
    id: "notes",
    label: "Notes",
    labelKn: "ಟಿಪ್ಪಣಿಗಳು",
    description: "Chapter notes, summaries, Kannada explanations",
    icon: "FileText",
    order: 3,
  },
  {
    id: "worksheet",
    label: "Worksheets",
    labelKn: "ಕಾರ್ಯಹಾಳೆಗಳು",
    description: "Practice sheets and assignments",
    icon: "ListChecks",
    order: 4,
  },
  {
    id: "video",
    label: "Videos",
    labelKn: "ವೀಡಿಯೊಗಳು",
    description: "Chapter explainers and revision videos",
    icon: "PlayCircle",
    order: 5,
  },
  {
    id: "formula",
    label: "Formula Bank",
    labelKn: "ಸೂತ್ರ ಸಂಗ್ರಹ",
    description: "Quick-reference formulas for Maths and Science",
    icon: "Sigma",
    order: 6,
  },
  {
    id: "qbank",
    label: "Question Banks",
    labelKn: "ಪ್ರಶ್ನಾವಳಿಗಳು",
    description: "Curated MCQs and short answers",
    icon: "Library",
    order: 7,
  },
  {
    id: "revision",
    label: "Revision Materials",
    labelKn: "ಪುನರ್ ಪರಿಶೀಲನೆ",
    description: "Cheat sheets, mind maps, last-minute revision",
    icon: "Sparkles",
    order: 8,
  },
];

/**
 * A small starter set so the page is never empty. Real content is added
 * via the admin import tab. URLs point to official KTBS / NCERT pages.
 */
export const STARTER_LIBRARY_RESOURCES: LibraryResourceDoc[] = [
  // ----- Karnataka KTBS portal (subject-wise, both mediums) -----
  {
    id: "ktbs_portal_home",
    title: "Karnataka Textbooks Portal (KTBS)",
    titleKn: "ಕರ್ನಾಟಕ ಪಠ್ಯಪುಸ್ತಕ ಪೋರ್ಟಲ್",
    description:
      "Official KSEAB / KTBS portal — download SSLC textbooks in Kannada and English medium.",
    category: "textbook",
    resourceType: "textbook",
    url: "https://textbooks.karnataka.gov.in/",
    language: "bilingual",
    tags: ["ktbs", "portal", "official"],
    isFeatured: true,
    isOfficial: true,
    views: 0,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "ncert_portal_home",
    title: "NCERT Textbooks Portal",
    description:
      "Official NCERT textbook downloads — reference books for Maths, Science and Social Science.",
    category: "textbook",
    resourceType: "textbook",
    url: "https://ncert.nic.in/textbook.php",
    language: "en",
    tags: ["ncert", "portal", "official", "reference"],
    isFeatured: true,
    isOfficial: true,
    views: 0,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "ktbs_sslc_math_en",
    title: "KTBS SSLC Mathematics (English)",
    titleKn: "ಕೆಟಿಬಿಎಸ್ ಎಸ್‌ಎಸ್‌ಎಲ್‌ಸಿ ಗಣಿತ",
    description: "Official Karnataka SSLC Mathematics textbook.",
    category: "textbook",
    resourceType: "textbook",
    subjectId: "math",
    url: "https://textbooks.karnataka.gov.in/",
    language: "en",
    tags: ["ktbs", "official", "math"],
    isFeatured: true,
    isOfficial: true,
    views: 0,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "ktbs_sslc_math_kn",
    title: "KTBS SSLC ಗಣಿತ (Kannada Medium)",
    titleKn: "ಎಸ್‌ಎಸ್‌ಎಲ್‌ಸಿ ಗಣಿತ",
    description: "ಕರ್ನಾಟಕ ಎಸ್‌ಎಸ್‌ಎಲ್‌ಸಿ ಗಣಿತ ಪಠ್ಯಪುಸ್ತಕ (ಕನ್ನಡ ಮಾಧ್ಯಮ).",
    category: "textbook",
    resourceType: "textbook",
    subjectId: "math",
    url: "https://textbooks.karnataka.gov.in/",
    language: "kn",
    tags: ["ktbs", "official", "math", "kannada-medium"],
    isFeatured: true,
    isOfficial: true,
    views: 0,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "ktbs_sslc_science_en",
    title: "KTBS SSLC Science (English)",
    titleKn: "ಕೆಟಿಬಿಎಸ್ ಎಸ್‌ಎಸ್‌ಎಲ್‌ಸಿ ವಿಜ್ಞಾನ",
    description: "Official Karnataka SSLC Science textbook.",
    category: "textbook",
    resourceType: "textbook",
    subjectId: "science",
    url: "https://textbooks.karnataka.gov.in/",
    language: "en",
    tags: ["ktbs", "official", "science"],
    isFeatured: true,
    isOfficial: true,
    views: 0,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "ktbs_sslc_science_kn",
    title: "KTBS SSLC ವಿಜ್ಞಾನ (Kannada Medium)",
    description: "ಕರ್ನಾಟಕ ಎಸ್‌ಎಸ್‌ಎಲ್‌ಸಿ ವಿಜ್ಞಾನ ಪಠ್ಯಪುಸ್ತಕ (ಕನ್ನಡ ಮಾಧ್ಯಮ).",
    category: "textbook",
    resourceType: "textbook",
    subjectId: "science",
    url: "https://textbooks.karnataka.gov.in/",
    language: "kn",
    tags: ["ktbs", "official", "science", "kannada-medium"],
    isFeatured: true,
    isOfficial: true,
    views: 0,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "ktbs_sslc_social_en",
    title: "KTBS SSLC Social Science",
    category: "textbook",
    resourceType: "textbook",
    subjectId: "social",
    url: "https://textbooks.karnataka.gov.in/",
    language: "bilingual",
    tags: ["ktbs", "official", "social"],
    isFeatured: true,
    isOfficial: true,
    views: 0,
    createdAt: 0,
    updatedAt: 0,
  },
  // ----- NCERT reference books (subject-wise) -----
  {
    id: "ncert_sslc_math",
    title: "NCERT Class 10 Mathematics",
    description: "NCERT reference textbook for Class 10 Maths.",
    category: "textbook",
    resourceType: "textbook",
    subjectId: "math",
    url: "https://ncert.nic.in/textbook.php",
    language: "en",
    tags: ["ncert", "official", "math", "reference"],
    isFeatured: false,
    isOfficial: true,
    views: 0,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "ncert_sslc_science",
    title: "NCERT Class 10 Science",
    description: "NCERT reference textbook for Class 10 Science.",
    category: "textbook",
    resourceType: "textbook",
    subjectId: "science",
    url: "https://ncert.nic.in/textbook.php",
    language: "en",
    tags: ["ncert", "official", "science", "reference"],
    isFeatured: false,
    isOfficial: true,
    views: 0,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "ncert_sslc_social",
    title: "NCERT Class 10 Social Science",
    description: "NCERT reference textbooks for Class 10 Social Science.",
    category: "textbook",
    resourceType: "textbook",
    subjectId: "social",
    url: "https://ncert.nic.in/textbook.php",
    language: "en",
    tags: ["ncert", "official", "social", "reference"],
    isFeatured: false,
    isOfficial: true,
    views: 0,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "kseab_model_papers_2024",
    title: "KSEAB Model Question Papers 2024",
    description: "Official model papers from the Karnataka School Examination and Assessment Board.",
    category: "pyq",
    resourceType: "pyq",
    url: "https://kseab.karnataka.gov.in/",
    language: "bilingual",
    tags: ["kseab", "model-paper", "2024"],
    isFeatured: true,
    isOfficial: true,
    year: 2024,
    views: 0,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "formula_bank_math",
    title: "SSLC Math Formula Sheet",
    description: "All chapter-wise formulas in a single quick-reference PDF.",
    category: "formula",
    resourceType: "revision",
    subjectId: "math",
    url: "https://textbooks.karnataka.gov.in/",
    language: "en",
    tags: ["formulas", "revision", "math"],
    isFeatured: true,
    isOfficial: false,
    views: 0,
    createdAt: 0,
    updatedAt: 0,
  },
];
