import type { SyllabusImportPayload } from "./types";
import { KARNATAKA_SSLC_MATH } from "./sslc-math";

// Canonical Karnataka SSLC Mathematics chapters (14, KSEAB/NCERT rationalised).
// Re-exported from the detailed math preset to keep a single source of truth —
// avoids duplicate / mis-ordered / deprecated entries (e.g. "Constructions" was
// dropped in the rationalised syllabus).
const MATH_SUBJECT = KARNATAKA_SSLC_MATH.subjects[0];

/**
 * Karnataka SSLC (Class 10) syllabus — KSEAB board.
 * Source of truth for the seed/import. Edit here, then re-run admin import.
 */
export const KARNATAKA_SSLC: SyllabusImportPayload = {
  board: "Karnataka SSLC",
  subjects: [
    MATH_SUBJECT,
    {
      id: "science",
      name: "Science",
      nameKn: "ವಿಜ್ಞಾನ",
      emoji: "🧪",
      color: "oklch(0.65 0.16 145)",
      target: 92,
      chapters: [
        { chapterNumber: 1, chapterName: "Chemical Reactions and Equations", difficulty: "Medium", estimatedStudyTime: 180, mcqCount: 20 },
        { chapterNumber: 2, chapterName: "Acids, Bases and Salts", difficulty: "Medium", estimatedStudyTime: 210, mcqCount: 22 },
        { chapterNumber: 3, chapterName: "Metals and Non-metals", difficulty: "Medium", estimatedStudyTime: 210, mcqCount: 22 },
        { chapterNumber: 4, chapterName: "Carbon and its Compounds", difficulty: "Hard", estimatedStudyTime: 240, mcqCount: 25 },
        { chapterNumber: 5, chapterName: "Periodic Classification of Elements", difficulty: "Medium", estimatedStudyTime: 180, mcqCount: 18 },
        { chapterNumber: 6, chapterName: "Life Processes", difficulty: "Medium", estimatedStudyTime: 240, mcqCount: 25 },
        { chapterNumber: 7, chapterName: "Control and Coordination", difficulty: "Medium", estimatedStudyTime: 210, mcqCount: 20 },
        { chapterNumber: 8, chapterName: "How do Organisms Reproduce?", difficulty: "Medium", estimatedStudyTime: 210, mcqCount: 20 },
        { chapterNumber: 9, chapterName: "Heredity and Evolution", difficulty: "Hard", estimatedStudyTime: 210, mcqCount: 20 },
        { chapterNumber: 10, chapterName: "Light — Reflection and Refraction", difficulty: "Medium", estimatedStudyTime: 240, mcqCount: 25 },
        { chapterNumber: 11, chapterName: "Human Eye and the Colourful World", difficulty: "Easy", estimatedStudyTime: 150, mcqCount: 18 },
        { chapterNumber: 12, chapterName: "Electricity", difficulty: "Hard", estimatedStudyTime: 270, mcqCount: 28 },
        { chapterNumber: 13, chapterName: "Magnetic Effects of Electric Current", difficulty: "Hard", estimatedStudyTime: 210, mcqCount: 22 },
        { chapterNumber: 14, chapterName: "Sources of Energy", difficulty: "Easy", estimatedStudyTime: 150, mcqCount: 15 },
        { chapterNumber: 15, chapterName: "Our Environment", difficulty: "Easy", estimatedStudyTime: 150, mcqCount: 15 },
        { chapterNumber: 16, chapterName: "Sustainable Management of Natural Resources", difficulty: "Easy", estimatedStudyTime: 150, mcqCount: 15 },
      ],
    },
    {
      id: "social",
      name: "Social Science",
      nameKn: "ಸಮಾಜ ವಿಜ್ಞಾನ",
      emoji: "🌍",
      color: "oklch(0.68 0.15 60)",
      target: 90,
      chapters: [
        { chapterNumber: 1, chapterName: "The Rise of Nationalism in Europe", difficulty: "Medium", estimatedStudyTime: 180, mcqCount: 18 },
        { chapterNumber: 2, chapterName: "Nationalism in India", difficulty: "Medium", estimatedStudyTime: 210, mcqCount: 22 },
        { chapterNumber: 3, chapterName: "The Making of a Global World", difficulty: "Medium", estimatedStudyTime: 180, mcqCount: 18 },
        { chapterNumber: 4, chapterName: "The Age of Industrialisation", difficulty: "Medium", estimatedStudyTime: 180, mcqCount: 18 },
        { chapterNumber: 5, chapterName: "Print Culture and the Modern World", difficulty: "Easy", estimatedStudyTime: 150, mcqCount: 15 },
        { chapterNumber: 6, chapterName: "Resources and Development", difficulty: "Easy", estimatedStudyTime: 150, mcqCount: 18 },
        { chapterNumber: 7, chapterName: "Forest and Wildlife Resources", difficulty: "Medium", estimatedStudyTime: 150, mcqCount: 15 },
        { chapterNumber: 8, chapterName: "Water Resources", difficulty: "Easy", estimatedStudyTime: 150, mcqCount: 15 },
        { chapterNumber: 9, chapterName: "Agriculture", difficulty: "Medium", estimatedStudyTime: 180, mcqCount: 18 },
        { chapterNumber: 10, chapterName: "Minerals and Energy Resources", difficulty: "Medium", estimatedStudyTime: 180, mcqCount: 18 },
        { chapterNumber: 11, chapterName: "Manufacturing Industries", difficulty: "Medium", estimatedStudyTime: 180, mcqCount: 18 },
        { chapterNumber: 12, chapterName: "Lifelines of National Economy", difficulty: "Easy", estimatedStudyTime: 150, mcqCount: 15 },
        { chapterNumber: 13, chapterName: "Power Sharing", difficulty: "Easy", estimatedStudyTime: 120, mcqCount: 12 },
        { chapterNumber: 14, chapterName: "Federalism", difficulty: "Medium", estimatedStudyTime: 150, mcqCount: 15 },
        { chapterNumber: 15, chapterName: "Democracy and Diversity", difficulty: "Medium", estimatedStudyTime: 150, mcqCount: 15 },
        { chapterNumber: 16, chapterName: "Gender, Religion and Caste", difficulty: "Medium", estimatedStudyTime: 150, mcqCount: 15 },
        { chapterNumber: 17, chapterName: "Popular Struggles and Movements", difficulty: "Medium", estimatedStudyTime: 150, mcqCount: 15 },
        { chapterNumber: 18, chapterName: "Political Parties", difficulty: "Easy", estimatedStudyTime: 150, mcqCount: 15 },
        { chapterNumber: 19, chapterName: "Outcomes of Democracy", difficulty: "Medium", estimatedStudyTime: 150, mcqCount: 15 },
        { chapterNumber: 20, chapterName: "Challenges to Democracy", difficulty: "Medium", estimatedStudyTime: 150, mcqCount: 12 },
        { chapterNumber: 21, chapterName: "Development", difficulty: "Medium", estimatedStudyTime: 150, mcqCount: 15 },
        { chapterNumber: 22, chapterName: "Sectors of the Indian Economy", difficulty: "Medium", estimatedStudyTime: 180, mcqCount: 18 },
        { chapterNumber: 23, chapterName: "Money and Credit", difficulty: "Hard", estimatedStudyTime: 180, mcqCount: 18 },
        { chapterNumber: 24, chapterName: "Globalisation and the Indian Economy", difficulty: "Medium", estimatedStudyTime: 180, mcqCount: 18 },
      ],
    },
    {
      id: "english",
      name: "English",
      nameKn: "ಇಂಗ್ಲಿಷ್",
      emoji: "📘",
      color: "oklch(0.6 0.17 310)",
      target: 90,
      chapters: [
        { chapterNumber: 1, chapterName: "A Letter to God", difficulty: "Easy", estimatedStudyTime: 120, mcqCount: 12 },
        { chapterNumber: 2, chapterName: "Nelson Mandela: Long Walk to Freedom", difficulty: "Medium", estimatedStudyTime: 150, mcqCount: 15 },
        { chapterNumber: 3, chapterName: "Two Stories about Flying", difficulty: "Medium", estimatedStudyTime: 150, mcqCount: 15 },
        { chapterNumber: 4, chapterName: "From the Diary of Anne Frank", difficulty: "Medium", estimatedStudyTime: 150, mcqCount: 15 },
        { chapterNumber: 5, chapterName: "Glimpses of India", difficulty: "Easy", estimatedStudyTime: 120, mcqCount: 12 },
        { chapterNumber: 6, chapterName: "Mijbil the Otter", difficulty: "Easy", estimatedStudyTime: 120, mcqCount: 12 },
        { chapterNumber: 7, chapterName: "Madam Rides the Bus", difficulty: "Easy", estimatedStudyTime: 120, mcqCount: 12 },
        { chapterNumber: 8, chapterName: "The Sermon at Benares", difficulty: "Medium", estimatedStudyTime: 120, mcqCount: 12 },
        { chapterNumber: 9, chapterName: "The Proposal", difficulty: "Medium", estimatedStudyTime: 150, mcqCount: 12 },
        { chapterNumber: 10, chapterName: "Grammar — Tenses & Reported Speech", difficulty: "Hard", estimatedStudyTime: 180, mcqCount: 25 },
        { chapterNumber: 11, chapterName: "Writing — Letters & Essays", difficulty: "Medium", estimatedStudyTime: 150, mcqCount: 10 },
        { chapterNumber: 12, chapterName: "Poetry Section", difficulty: "Medium", estimatedStudyTime: 180, mcqCount: 18 },
      ],
    },
    {
      id: "kannada",
      name: "Kannada (Second Language)",
      nameKn: "ಕನ್ನಡ",
      emoji: "ಕ",
      color: "oklch(0.62 0.18 25)",
      target: 95,
      chapters: [
        { chapterNumber: 1, chapterName: "ಶಬರಿ", difficulty: "Medium", estimatedStudyTime: 150, mcqCount: 12 },
        { chapterNumber: 2, chapterName: "ಹೊಸ ಹಾಡು", difficulty: "Medium", estimatedStudyTime: 150, mcqCount: 12 },
        { chapterNumber: 3, chapterName: "ವಚನ ಸಾಹಿತ್ಯ", difficulty: "Medium", estimatedStudyTime: 180, mcqCount: 15 },
        { chapterNumber: 4, chapterName: "ಭಾಗ್ಯಶಿಲ್ಪಿಗಳು", difficulty: "Easy", estimatedStudyTime: 120, mcqCount: 12 },
        { chapterNumber: 5, chapterName: "ಬಸವಣ್ಣನವರ ಜೀವನ", difficulty: "Easy", estimatedStudyTime: 120, mcqCount: 12 },
        { chapterNumber: 6, chapterName: "ವ್ಯಾಕರಣ — ಸಂಧಿ", difficulty: "Hard", estimatedStudyTime: 180, mcqCount: 20 },
        { chapterNumber: 7, chapterName: "ಪತ್ರ ಲೇಖನ", difficulty: "Medium", estimatedStudyTime: 120, mcqCount: 10 },
        { chapterNumber: 8, chapterName: "ಪ್ರಬಂಧ ರಚನೆ", difficulty: "Medium", estimatedStudyTime: 150, mcqCount: 10 },
        { chapterNumber: 9, chapterName: "ಪದ್ಯ ವಿಮರ್ಶೆ", difficulty: "Medium", estimatedStudyTime: 180, mcqCount: 15 },
      ],
    },
    {
      id: "hindi",
      name: "Hindi / Urdu (Third Language)",
      nameKn: "ಹಿಂದಿ / ಉರ್ದು",
      emoji: "ह",
      color: "oklch(0.65 0.16 20)",
      target: 85,
      chapters: [
        { chapterNumber: 1, chapterName: "गद्य — कबीर के दोहे", difficulty: "Medium", estimatedStudyTime: 150, mcqCount: 12 },
        { chapterNumber: 2, chapterName: "मीराबाई", difficulty: "Medium", estimatedStudyTime: 150, mcqCount: 12 },
        { chapterNumber: 3, chapterName: "बिहारी के दोहे", difficulty: "Medium", estimatedStudyTime: 150, mcqCount: 12 },
        { chapterNumber: 4, chapterName: "मैथिलीशरण गुप्त", difficulty: "Medium", estimatedStudyTime: 150, mcqCount: 12 },
        { chapterNumber: 5, chapterName: "साखी", difficulty: "Easy", estimatedStudyTime: 120, mcqCount: 10 },
        { chapterNumber: 6, chapterName: "व्याकरण — संधि", difficulty: "Hard", estimatedStudyTime: 180, mcqCount: 18 },
        { chapterNumber: 7, chapterName: "व्याकरण — समास", difficulty: "Hard", estimatedStudyTime: 180, mcqCount: 18 },
        { chapterNumber: 8, chapterName: "अनुवाद", difficulty: "Hard", estimatedStudyTime: 180, mcqCount: 15 },
        { chapterNumber: 9, chapterName: "पत्र लेखन", difficulty: "Easy", estimatedStudyTime: 120, mcqCount: 10 },
      ],
    },
  ],
};