import type { SyllabusImportPayload, SyllabusChapterInput } from "./types";

/**
 * Karnataka SSLC — Mathematics (Class 10, KSEAB / NCERT rationalised).
 * Rich, AI-ready dataset: each chapter ships topics, formulas and learning
 * objectives so downstream features (MCQ generation, weak-topic analysis,
 * revision planner, AI recommendations) can reason over structured data
 * rather than free-form text.
 */

const chapters: SyllabusChapterInput[] = [
  {
    chapterNumber: 1,
    chapterName: "Real Numbers",
    chapterNameKn: "ವಾಸ್ತವ ಸಂಖ್ಯೆಗಳು",
    difficulty: "Easy",
    estimatedStudyTime: 150,
    mcqCount: 15,
    textbookUrl: "https://ncert.nic.in/textbook/pdf/jemh101.pdf",
    notesUrl: "",
    worksheetUrl: "",
    videoUrls: [],
    importantTopics: [
      "Euclid's Division Lemma",
      "Fundamental Theorem of Arithmetic",
      "HCF and LCM by prime factorisation",
      "Irrational numbers (√2, √3, √5)",
    ],
    formulas: [
      { label: "HCF × LCM", expression: "HCF(a,b) × LCM(a,b) = a × b", description: "Holds for any two positive integers." },
    ],
    learningObjectives: [
      "Prove √2, √3, √5 are irrational",
      "Compute HCF and LCM via prime factorisation",
      "Apply the Fundamental Theorem of Arithmetic",
    ],
  },
  {
    chapterNumber: 2,
    chapterName: "Polynomials",
    chapterNameKn: "ಬಹುಪದಗಳು",
    difficulty: "Medium",
    estimatedStudyTime: 180,
    mcqCount: 18,
    textbookUrl: "https://ncert.nic.in/textbook/pdf/jemh102.pdf",
    notesUrl: "",
    worksheetUrl: "",
    videoUrls: [],
    importantTopics: [
      "Zeros of a polynomial",
      "Relationship between zeros and coefficients",
      "Geometric meaning of zeros",
    ],
    formulas: [
      { label: "Sum of zeros (quadratic)", expression: "α + β = -b/a" },
      { label: "Product of zeros (quadratic)", expression: "αβ = c/a" },
    ],
    learningObjectives: [
      "Identify zeros from a graph",
      "Derive coefficient–zero relations for quadratics and cubics",
    ],
  },
  {
    chapterNumber: 3,
    chapterName: "Pair of Linear Equations in Two Variables",
    chapterNameKn: "ಎರಡು ಚರಾಕ್ಷರಗಳಲ್ಲಿ ರೇಖೀಯ ಸಮೀಕರಣಗಳ ಜೋಡಿ",
    difficulty: "Medium",
    estimatedStudyTime: 210,
    mcqCount: 20,
    textbookUrl: "https://ncert.nic.in/textbook/pdf/jemh103.pdf",
    notesUrl: "",
    worksheetUrl: "",
    videoUrls: [],
    importantTopics: [
      "Graphical method",
      "Substitution method",
      "Elimination method",
      "Cross-multiplication method",
      "Consistency conditions",
    ],
    formulas: [
      { label: "Unique solution", expression: "a₁/a₂ ≠ b₁/b₂" },
      { label: "Infinite solutions", expression: "a₁/a₂ = b₁/b₂ = c₁/c₂" },
      { label: "No solution", expression: "a₁/a₂ = b₁/b₂ ≠ c₁/c₂" },
    ],
    learningObjectives: [
      "Solve linear pairs algebraically and graphically",
      "Classify systems as consistent / inconsistent",
      "Model word problems as linear pairs",
    ],
  },
  {
    chapterNumber: 4,
    chapterName: "Quadratic Equations",
    chapterNameKn: "ವರ್ಗ ಸಮೀಕರಣಗಳು",
    difficulty: "Hard",
    estimatedStudyTime: 240,
    mcqCount: 25,
    textbookUrl: "https://ncert.nic.in/textbook/pdf/jemh104.pdf",
    notesUrl: "",
    worksheetUrl: "",
    videoUrls: [],
    importantTopics: [
      "Factorisation method",
      "Completing the square",
      "Quadratic formula",
      "Nature of roots via discriminant",
    ],
    formulas: [
      { label: "Quadratic formula", expression: "x = (-b ± √(b² - 4ac)) / 2a" },
      { label: "Discriminant", expression: "D = b² - 4ac" },
    ],
    learningObjectives: [
      "Solve quadratics by three methods",
      "Determine nature of roots from D",
      "Translate real-world problems into quadratic form",
    ],
  },
  {
    chapterNumber: 5,
    chapterName: "Arithmetic Progressions",
    chapterNameKn: "ಸಮಾಂತರ ಶ್ರೇಢಿಗಳು",
    difficulty: "Medium",
    estimatedStudyTime: 180,
    mcqCount: 20,
    textbookUrl: "https://ncert.nic.in/textbook/pdf/jemh105.pdf",
    notesUrl: "",
    worksheetUrl: "",
    videoUrls: [],
    importantTopics: [
      "General form of an AP",
      "nth term",
      "Sum of first n terms",
      "Word problems on APs",
    ],
    formulas: [
      { label: "nth term", expression: "aₙ = a + (n - 1)d" },
      { label: "Sum of n terms", expression: "Sₙ = n/2 [2a + (n - 1)d]" },
      { label: "Sum given last term", expression: "Sₙ = n/2 (a + l)" },
    ],
    learningObjectives: [
      "Identify an AP and its common difference",
      "Compute aₙ and Sₙ",
      "Apply APs to real-life sequences",
    ],
  },
  {
    chapterNumber: 6,
    chapterName: "Triangles",
    chapterNameKn: "ತ್ರಿಭುಜಗಳು",
    difficulty: "Medium",
    estimatedStudyTime: 240,
    mcqCount: 25,
    textbookUrl: "https://ncert.nic.in/textbook/pdf/jemh106.pdf",
    notesUrl: "",
    worksheetUrl: "",
    videoUrls: [],
    importantTopics: [
      "Similarity of triangles",
      "Basic Proportionality Theorem (Thales)",
      "Criteria for similarity (AAA, SSS, SAS)",
      "Areas of similar triangles",
      "Pythagoras Theorem",
    ],
    formulas: [
      { label: "Pythagoras", expression: "a² + b² = c²" },
      { label: "Area ratio of similar Δ", expression: "A₁/A₂ = (s₁/s₂)²" },
    ],
    learningObjectives: [
      "Prove Thales and its converse",
      "Apply similarity criteria",
      "Use Pythagoras in proofs and applications",
    ],
  },
  {
    chapterNumber: 7,
    chapterName: "Coordinate Geometry",
    chapterNameKn: "ನಿರ್ದೇಶಾಂಕ ರೇಖಾಗಣಿತ",
    difficulty: "Medium",
    estimatedStudyTime: 210,
    mcqCount: 20,
    textbookUrl: "https://ncert.nic.in/textbook/pdf/jemh107.pdf",
    notesUrl: "",
    worksheetUrl: "",
    videoUrls: [],
    importantTopics: [
      "Distance formula",
      "Section formula",
      "Midpoint formula",
      "Area of a triangle from coordinates",
    ],
    formulas: [
      { label: "Distance", expression: "d = √((x₂ - x₁)² + (y₂ - y₁)²)" },
      { label: "Section formula", expression: "P = ((mx₂ + nx₁)/(m+n), (my₂ + ny₁)/(m+n))" },
      { label: "Midpoint", expression: "M = ((x₁ + x₂)/2, (y₁ + y₂)/2)" },
    ],
    learningObjectives: [
      "Compute distance, midpoint and section points",
      "Find areas using the coordinate formula",
      "Verify collinearity",
    ],
  },
  {
    chapterNumber: 8,
    chapterName: "Introduction to Trigonometry",
    chapterNameKn: "ತ್ರಿಕೋನಮಿತಿಯ ಪರಿಚಯ",
    difficulty: "Medium",
    estimatedStudyTime: 210,
    mcqCount: 20,
    textbookUrl: "https://ncert.nic.in/textbook/pdf/jemh108.pdf",
    notesUrl: "",
    worksheetUrl: "",
    videoUrls: [],
    importantTopics: [
      "Trigonometric ratios",
      "Ratios of specific angles (0°, 30°, 45°, 60°, 90°)",
      "Trigonometric identities",
    ],
    formulas: [
      { label: "Identity 1", expression: "sin²θ + cos²θ = 1" },
      { label: "Identity 2", expression: "1 + tan²θ = sec²θ" },
      { label: "Identity 3", expression: "1 + cot²θ = cosec²θ" },
    ],
    learningObjectives: [
      "Define sin, cos, tan and reciprocals",
      "Prove and apply Pythagorean identities",
      "Evaluate trig expressions at standard angles",
    ],
  },
  {
    chapterNumber: 9,
    chapterName: "Some Applications of Trigonometry",
    chapterNameKn: "ತ್ರಿಕೋನಮಿತಿಯ ಅನ್ವಯಗಳು",
    difficulty: "Hard",
    estimatedStudyTime: 180,
    mcqCount: 15,
    textbookUrl: "https://ncert.nic.in/textbook/pdf/jemh109.pdf",
    notesUrl: "",
    worksheetUrl: "",
    videoUrls: [],
    importantTopics: [
      "Heights and distances",
      "Angle of elevation",
      "Angle of depression",
    ],
    formulas: [
      { label: "Tan of angle of elevation", expression: "tan θ = opposite / adjacent" },
    ],
    learningObjectives: [
      "Model elevation/depression problems",
      "Solve heights & distances using right-triangle trig",
    ],
  },
  {
    chapterNumber: 10,
    chapterName: "Circles",
    chapterNameKn: "ವೃತ್ತಗಳು",
    difficulty: "Medium",
    estimatedStudyTime: 180,
    mcqCount: 20,
    textbookUrl: "https://ncert.nic.in/textbook/pdf/jemh110.pdf",
    notesUrl: "",
    worksheetUrl: "",
    videoUrls: [],
    importantTopics: [
      "Tangent to a circle",
      "Number of tangents from an external point",
      "Length of tangents",
    ],
    formulas: [
      { label: "Tangent-radius angle", expression: "Tangent ⟂ radius at point of contact" },
      { label: "Equal tangents", expression: "PA = PB (from external point P)" },
    ],
    learningObjectives: [
      "Prove tangent properties",
      "Compute tangent lengths from an external point",
    ],
  },
  {
    chapterNumber: 11,
    chapterName: "Areas Related to Circles",
    chapterNameKn: "ವೃತ್ತಗಳಿಗೆ ಸಂಬಂಧಿಸಿದ ವಿಸ್ತೀರ್ಣಗಳು",
    difficulty: "Medium",
    estimatedStudyTime: 180,
    mcqCount: 18,
    textbookUrl: "https://ncert.nic.in/textbook/pdf/jemh111.pdf",
    notesUrl: "",
    worksheetUrl: "",
    videoUrls: [],
    importantTopics: [
      "Area and circumference of a circle",
      "Area of sector and segment",
      "Combinations of plane figures",
    ],
    formulas: [
      { label: "Area of circle", expression: "A = πr²" },
      { label: "Circumference", expression: "C = 2πr" },
      { label: "Area of sector", expression: "A = (θ/360) × πr²" },
      { label: "Length of arc", expression: "l = (θ/360) × 2πr" },
    ],
    learningObjectives: [
      "Compute sector and segment areas",
      "Find areas of combined plane figures",
    ],
  },
  {
    chapterNumber: 12,
    chapterName: "Surface Areas and Volumes",
    chapterNameKn: "ಮೇಲ್ಮೈ ವಿಸ್ತೀರ್ಣ ಮತ್ತು ಘನಫಲಗಳು",
    difficulty: "Hard",
    estimatedStudyTime: 240,
    mcqCount: 22,
    textbookUrl: "https://ncert.nic.in/textbook/pdf/jemh112.pdf",
    notesUrl: "",
    worksheetUrl: "",
    videoUrls: [],
    importantTopics: [
      "Surface area of combined solids",
      "Volume of combined solids",
      "Conversion of solids",
    ],
    formulas: [
      { label: "Volume of cylinder", expression: "V = πr²h" },
      { label: "Volume of cone", expression: "V = (1/3)πr²h" },
      { label: "Volume of sphere", expression: "V = (4/3)πr³" },
      { label: "Volume of hemisphere", expression: "V = (2/3)πr³" },
    ],
    learningObjectives: [
      "Decompose composite solids",
      "Apply volume conservation in conversions",
    ],
  },
  {
    chapterNumber: 13,
    chapterName: "Statistics",
    chapterNameKn: "ಸಂಖ್ಯಾಶಾಸ್ತ್ರ",
    difficulty: "Easy",
    estimatedStudyTime: 180,
    mcqCount: 20,
    textbookUrl: "https://ncert.nic.in/textbook/pdf/jemh113.pdf",
    notesUrl: "",
    worksheetUrl: "",
    videoUrls: [],
    importantTopics: [
      "Mean of grouped data (direct, assumed-mean, step-deviation)",
      "Mode of grouped data",
      "Median of grouped data",
      "Cumulative frequency curves (ogives)",
    ],
    formulas: [
      { label: "Mean (direct)", expression: "x̄ = Σfᵢxᵢ / Σfᵢ" },
      { label: "Mode", expression: "Mode = l + ((f₁ - f₀)/(2f₁ - f₀ - f₂)) × h" },
      { label: "Median", expression: "Median = l + ((n/2 - cf)/f) × h" },
    ],
    learningObjectives: [
      "Compute central tendency for grouped data",
      "Construct and read ogives",
    ],
  },
  {
    chapterNumber: 14,
    chapterName: "Probability",
    chapterNameKn: "ಸಂಭವನೀಯತೆ",
    difficulty: "Medium",
    estimatedStudyTime: 150,
    mcqCount: 15,
    textbookUrl: "https://ncert.nic.in/textbook/pdf/jemh114.pdf",
    notesUrl: "",
    worksheetUrl: "",
    videoUrls: [],
    importantTopics: [
      "Classical probability",
      "Equally likely outcomes",
      "Complementary events",
    ],
    formulas: [
      { label: "Probability", expression: "P(E) = favourable outcomes / total outcomes" },
      { label: "Complement", expression: "P(not E) = 1 - P(E)" },
    ],
    learningObjectives: [
      "Compute classical probabilities",
      "Use complement rule",
      "Solve dice / card / coin problems",
    ],
  },
];

export const KARNATAKA_SSLC_MATH: SyllabusImportPayload = {
  board: "Karnataka SSLC — Mathematics",
  subjects: [
    {
      id: "math",
      name: "Mathematics",
      nameKn: "ಗಣಿತ",
      emoji: "📐",
      color: "oklch(0.6 0.18 250)",
      target: 95,
      chapters,
    },
  ],
};