import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/privacy")({
  component: PrivacyPage,
  head: () => ({
    meta: [
      { title: "Privacy Policy — Aura" },
      {
        name: "description",
        content:
          "How Aura collects, stores and protects student data, including AI transparency, parent and teacher access, and account deletion.",
      },
    ],
  }),
});

function PrivacyPage() {
  return (
    <div className="mx-auto max-w-2xl space-y-6 p-6 text-sm leading-relaxed">
      <header>
        <h1 className="text-2xl font-semibold">Privacy Policy</h1>
        <p className="text-muted-foreground">Last updated: 2026</p>
      </header>

      <section className="space-y-2">
        <h2 className="text-lg font-medium">1. Who we are</h2>
        <p>
          Aura is an AI study companion built for Karnataka SSLC students. We
          collect only what is needed to personalize learning and to keep
          parents and teachers informed.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-medium">2. What we collect</h2>
        <ul className="list-disc space-y-1 pl-5">
          <li>Account details (name, email, class, board, optional school).</li>
          <li>Learning activity (scans, quizzes, planner tasks, sessions).</li>
          <li>Voice transcripts when you actively use the voice tutor.</li>
          <li>Device + diagnostic data needed to keep the app stable.</li>
        </ul>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-medium">3. AI transparency</h2>
        <p>
          Tutoring, evaluation and explanations are generated by AI models.
          Outputs may occasionally contain mistakes; always confirm important
          answers with your teacher or textbook. We never sell student data
          and never use it to train third-party models.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-medium">4. Permissions</h2>
        <p>
          Camera and microphone access are requested only when needed
          (scanning a question, talking to the voice tutor) and can be
          revoked at any time from your device settings.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-medium">5. Parent &amp; teacher access</h2>
        <p>
          Parents and teachers see summaries only — never raw chats. Linking
          requires a code generated by the student.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-medium">6. Account deletion</h2>
        <p>
          You can permanently delete your account and all linked data at any
          time from{" "}
          <Link
            to="/account/delete"
            className="text-primary underline-offset-4 hover:underline"
          >
            Account &gt; Delete account
          </Link>
          . Local data is purged immediately; server data is removed within 30 days.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-medium">7. Contact</h2>
        <p>
          For privacy questions or data export, write to{" "}
          <a className="underline" href="mailto:privacy@aura.app">
            privacy@aura.app
          </a>
          .
        </p>
      </section>
    </div>
  );
}