/**
 * Mathematics Question Bank — Karnataka SSLC 10th Grade
 * Chapters: Real Numbers, Polynomials, Linear Equations, Quadratic Equations,
 *           Arithmetic Progressions, Triangles, Coordinate Geometry,
 *           Trigonometry, Circles, Statistics, Probability
 */

import type { Question } from "@/hooks/use-exam-engine";

// ---------------------------------------------------------------------------
// Real Numbers
// ---------------------------------------------------------------------------
export const realNumbers: Question[] = [
  {
    id: "math-real-001",
    subject: "Mathematics",
    chapter: "Real Numbers",
    concept: "Euclid's Division Lemma",
    difficulty: "easy",
    questionType: "mcq",
    marks: 1,
    question: "HCF of 26 and 91 using Euclid's division algorithm is:",
    options: ["13", "26", "91", "1"],
    correctAnswer: "13",
    explanation: "91 = 26 × 3 + 13, then 26 = 13 × 2 + 0. Since remainder is 0, HCF = 13.",
    cognitiveLevel: "apply",
  },
  {
    id: "math-real-002",
    subject: "Mathematics",
    chapter: "Real Numbers",
    concept: "Irrational Numbers",
    difficulty: "easy",
    questionType: "mcq",
    marks: 1,
    question: "Which of the following is an irrational number?",
    options: ["√4", "√9", "√7", "√16"],
    correctAnswer: "√7",
    explanation: "√7 cannot be expressed as p/q (where p, q are integers and q ≠ 0), so it is irrational. √4 = 2, √9 = 3, √16 = 4 are all rational.",
    cognitiveLevel: "understand",
  },
  {
    id: "math-real-003",
    subject: "Mathematics",
    chapter: "Real Numbers",
    concept: "LCM and HCF",
    difficulty: "medium",
    questionType: "mcq",
    marks: 1,
    question: "If HCF(a, b) = 5 and LCM(a, b) = 60, then a × b =",
    options: ["300", "12", "65", "55"],
    correctAnswer: "300",
    explanation: "For any two positive integers a and b: a × b = HCF(a,b) × LCM(a,b) = 5 × 60 = 300.",
    cognitiveLevel: "apply",
    commonMistakes: ["Adding HCF and LCM instead of multiplying"],
  },
  {
    id: "math-real-004",
    subject: "Mathematics",
    chapter: "Real Numbers",
    concept: "Decimal Expansion",
    difficulty: "easy",
    questionType: "mcq",
    marks: 1,
    question: "The decimal expansion of 17/8 is:",
    options: ["Terminating", "Non-terminating repeating", "Non-terminating non-repeating", "Cannot be determined"],
    correctAnswer: "Terminating",
    explanation: "17/8 = 2.125. Since the denominator 8 = 2³ (only factor of 2), its decimal expansion terminates.",
    cognitiveLevel: "understand",
  },
];

// ---------------------------------------------------------------------------
// Polynomials
// ---------------------------------------------------------------------------
export const polynomials: Question[] = [
  {
    id: "math-poly-001",
    subject: "Mathematics",
    chapter: "Polynomials",
    concept: "Zeroes of a Polynomial",
    difficulty: "easy",
    questionType: "mcq",
    marks: 1,
    question: "If the zeroes of the quadratic polynomial x² + (a+1)x + b are 2 and -3, then:",
    options: ["a = -7, b = -1", "a = 5, b = -1", "a = 2, b = -6", "a = 0, b = -6"],
    correctAnswer: "a = 0, b = -6",
    explanation: "Sum of zeroes = 2 + (–3) = –1 = –(a+1)/1, so a+1 = 1 ⟹ a = 0. Product of zeroes = 2 × (–3) = –6 = b.",
    cognitiveLevel: "apply",
  },
  {
    id: "math-poly-002",
    subject: "Mathematics",
    chapter: "Polynomials",
    concept: "Relationship between Zeroes and Coefficients",
    difficulty: "easy",
    questionType: "mcq",
    marks: 1,
    question: "For the polynomial p(x) = 3x² – 5x + 2, the sum of its zeroes is:",
    options: ["5/3", "-5/3", "2/3", "-2/3"],
    correctAnswer: "5/3",
    explanation: "For ax² + bx + c, sum of zeroes = –b/a = –(–5)/3 = 5/3.",
    cognitiveLevel: "remember",
  },
  {
    id: "math-poly-003",
    subject: "Mathematics",
    chapter: "Polynomials",
    concept: "Number of Zeroes",
    difficulty: "easy",
    questionType: "mcq",
    marks: 1,
    question: "A quadratic polynomial can have at most how many zeroes?",
    options: ["1", "2", "3", "4"],
    correctAnswer: "2",
    explanation: "A polynomial of degree n has at most n zeroes. A quadratic polynomial has degree 2, so it has at most 2 zeroes.",
    cognitiveLevel: "remember",
  },
];

// ---------------------------------------------------------------------------
// Arithmetic Progressions
// ---------------------------------------------------------------------------
export const arithmeticProgressions: Question[] = [
  {
    id: "math-ap-001",
    subject: "Mathematics",
    chapter: "Arithmetic Progressions",
    concept: "nth Term",
    difficulty: "easy",
    questionType: "mcq",
    marks: 1,
    question: "The 10th term of the AP: 2, 7, 12, 17, ... is:",
    options: ["47", "42", "52", "45"],
    correctAnswer: "47",
    explanation: "a = 2, d = 5. aₙ = a + (n–1)d = 2 + (10–1)×5 = 2 + 45 = 47.",
    cognitiveLevel: "apply",
  },
  {
    id: "math-ap-002",
    subject: "Mathematics",
    chapter: "Arithmetic Progressions",
    concept: "Common Difference",
    difficulty: "easy",
    questionType: "mcq",
    marks: 1,
    question: "The common difference of the AP: 3, 1, –1, –3, ... is:",
    options: ["2", "–2", "3", "–3"],
    correctAnswer: "–2",
    explanation: "Common difference d = a₂ – a₁ = 1 – 3 = –2. Verify: 1 – 3 = –1 – 1 = –3 – (–1) = –2 ✓",
    cognitiveLevel: "remember",
  },
  {
    id: "math-ap-003",
    subject: "Mathematics",
    chapter: "Arithmetic Progressions",
    concept: "Sum of n Terms",
    difficulty: "medium",
    questionType: "mcq",
    marks: 1,
    question: "The sum of first 20 terms of the AP: 1, 3, 5, 7, ... is:",
    options: ["400", "200", "210", "420"],
    correctAnswer: "400",
    explanation: "Sₙ = n/2 × [2a + (n–1)d] = 20/2 × [2×1 + 19×2] = 10 × [2 + 38] = 10 × 40 = 400. (These are first 20 odd numbers and their sum = n² = 400).",
    cognitiveLevel: "apply",
    commonMistakes: ["Using wrong formula Sₙ = n(a+l)/2 without knowing last term"],
  },
  {
    id: "math-ap-004",
    subject: "Mathematics",
    chapter: "Arithmetic Progressions",
    concept: "nth Term",
    difficulty: "medium",
    questionType: "mcq",
    marks: 1,
    question: "Which term of the AP: 21, 18, 15, ... is –81?",
    options: ["32nd", "33rd", "34th", "35th"],
    correctAnswer: "35th",
    explanation: "a = 21, d = –3. aₙ = –81 ⟹ 21 + (n–1)(–3) = –81 ⟹ (n–1)(–3) = –102 ⟹ n–1 = 34 ⟹ n = 35.",
    cognitiveLevel: "apply",
  },
];

// ---------------------------------------------------------------------------
// Quadratic Equations
// ---------------------------------------------------------------------------
export const quadraticEquations: Question[] = [
  {
    id: "math-quad-001",
    subject: "Mathematics",
    chapter: "Quadratic Equations",
    concept: "Nature of Roots — Discriminant",
    difficulty: "medium",
    questionType: "mcq",
    marks: 1,
    question: "The discriminant of the equation 2x² – 4x + 3 = 0 is:",
    options: ["–8", "8", "–4", "28"],
    correctAnswer: "–8",
    explanation: "D = b² – 4ac = (–4)² – 4×2×3 = 16 – 24 = –8. Since D < 0, the equation has no real roots.",
    cognitiveLevel: "apply",
  },
  {
    id: "math-quad-002",
    subject: "Mathematics",
    chapter: "Quadratic Equations",
    concept: "Solving by Factorisation",
    difficulty: "easy",
    questionType: "mcq",
    marks: 1,
    question: "The roots of the quadratic equation x² – 5x + 6 = 0 are:",
    options: ["2 and 3", "–2 and –3", "2 and –3", "–2 and 3"],
    correctAnswer: "2 and 3",
    explanation: "x² – 5x + 6 = (x – 2)(x – 3) = 0. So x = 2 or x = 3. Verify: 2 + 3 = 5 = –(–5)/1 and 2×3 = 6 ✓",
    cognitiveLevel: "apply",
  },
  {
    id: "math-quad-003",
    subject: "Mathematics",
    chapter: "Quadratic Equations",
    concept: "Nature of Roots",
    difficulty: "easy",
    questionType: "mcq",
    marks: 1,
    question: "If D = 0 for a quadratic equation, then the roots are:",
    options: ["Real and distinct", "Real and equal", "Imaginary", "Rational and unequal"],
    correctAnswer: "Real and equal",
    explanation: "When discriminant D = b² – 4ac = 0, the quadratic has two equal real roots: x = –b/2a.",
    cognitiveLevel: "remember",
  },
];

// ---------------------------------------------------------------------------
// Triangles
// ---------------------------------------------------------------------------
export const triangles: Question[] = [
  {
    id: "math-tri-001",
    subject: "Mathematics",
    chapter: "Triangles",
    concept: "Similar Triangles — Basic Proportionality Theorem",
    difficulty: "medium",
    questionType: "mcq",
    marks: 1,
    question: "In ΔABC, D and E are points on AB and AC such that DE ∥ BC. If AD = 4 cm, DB = 6 cm and AE = 5 cm, then EC =",
    options: ["7.5 cm", "6 cm", "5 cm", "8 cm"],
    correctAnswer: "7.5 cm",
    explanation: "By BPT: AD/DB = AE/EC ⟹ 4/6 = 5/EC ⟹ EC = (5×6)/4 = 30/4 = 7.5 cm.",
    cognitiveLevel: "apply",
    commonMistakes: ["Setting up the proportion incorrectly as AD/AE = DB/EC"],
  },
  {
    id: "math-tri-002",
    subject: "Mathematics",
    chapter: "Triangles",
    concept: "Pythagoras Theorem",
    difficulty: "easy",
    questionType: "mcq",
    marks: 1,
    question: "In a right triangle, if one leg = 5 cm and hypotenuse = 13 cm, the other leg is:",
    options: ["12 cm", "8 cm", "10 cm", "11 cm"],
    correctAnswer: "12 cm",
    explanation: "By Pythagoras theorem: leg² = hypotenuse² – other leg² = 13² – 5² = 169 – 25 = 144. So leg = √144 = 12 cm.",
    cognitiveLevel: "apply",
  },
  {
    id: "math-tri-003",
    subject: "Mathematics",
    chapter: "Triangles",
    concept: "Area of Similar Triangles",
    difficulty: "medium",
    questionType: "mcq",
    marks: 1,
    question: "If ΔABC ~ ΔPQR and ar(ΔABC)/ar(ΔPQR) = 9/25, then AB/PQ =",
    options: ["3/5", "9/25", "81/625", "5/3"],
    correctAnswer: "3/5",
    explanation: "Ratio of areas of similar triangles = (ratio of corresponding sides)². So AB/PQ = √(9/25) = 3/5.",
    cognitiveLevel: "apply",
  },
];

// ---------------------------------------------------------------------------
// Coordinate Geometry
// ---------------------------------------------------------------------------
export const coordinateGeometry: Question[] = [
  {
    id: "math-coord-001",
    subject: "Mathematics",
    chapter: "Coordinate Geometry",
    concept: "Distance Formula",
    difficulty: "easy",
    questionType: "mcq",
    marks: 1,
    question: "The distance between the points A(2, 3) and B(5, 7) is:",
    options: ["5 units", "4 units", "3 units", "√7 units"],
    correctAnswer: "5 units",
    explanation: "d = √[(x₂–x₁)² + (y₂–y₁)²] = √[(5–2)² + (7–3)²] = √[9 + 16] = √25 = 5 units.",
    cognitiveLevel: "apply",
  },
  {
    id: "math-coord-002",
    subject: "Mathematics",
    chapter: "Coordinate Geometry",
    concept: "Section Formula",
    difficulty: "medium",
    questionType: "mcq",
    marks: 1,
    question: "The midpoint of the line segment joining A(3, 4) and B(7, 8) is:",
    options: ["(5, 6)", "(4, 5)", "(10, 12)", "(2, 2)"],
    correctAnswer: "(5, 6)",
    explanation: "Midpoint = ((x₁+x₂)/2, (y₁+y₂)/2) = ((3+7)/2, (4+8)/2) = (10/2, 12/2) = (5, 6).",
    cognitiveLevel: "apply",
  },
  {
    id: "math-coord-003",
    subject: "Mathematics",
    chapter: "Coordinate Geometry",
    concept: "Area of Triangle",
    difficulty: "medium",
    questionType: "mcq",
    marks: 1,
    question: "The area of the triangle with vertices (0, 0), (3, 0), and (0, 4) is:",
    options: ["6 sq. units", "12 sq. units", "7 sq. units", "3.5 sq. units"],
    correctAnswer: "6 sq. units",
    explanation: "Area = ½ × base × height = ½ × 3 × 4 = 6 sq. units. (Right triangle with legs 3 and 4).",
    cognitiveLevel: "apply",
  },
];

// ---------------------------------------------------------------------------
// Introduction to Trigonometry
// ---------------------------------------------------------------------------
export const trigonometry: Question[] = [
  {
    id: "math-trig-001",
    subject: "Mathematics",
    chapter: "Introduction to Trigonometry",
    concept: "Trigonometric Ratios",
    difficulty: "easy",
    questionType: "mcq",
    marks: 1,
    question: "If sin A = 3/5 in a right triangle, then cos A =",
    options: ["4/5", "3/4", "5/3", "5/4"],
    correctAnswer: "4/5",
    explanation: "If sin A = 3/5, then opposite = 3, hypotenuse = 5. By Pythagoras: adjacent = √(25–9) = 4. So cos A = 4/5.",
    cognitiveLevel: "apply",
  },
  {
    id: "math-trig-002",
    subject: "Mathematics",
    chapter: "Introduction to Trigonometry",
    concept: "Standard Values",
    difficulty: "easy",
    questionType: "mcq",
    marks: 1,
    question: "The value of sin 30° + cos 60° is:",
    options: ["1", "0", "√3/2", "1/√2"],
    correctAnswer: "1",
    explanation: "sin 30° = 1/2 and cos 60° = 1/2. So sin 30° + cos 60° = 1/2 + 1/2 = 1.",
    cognitiveLevel: "remember",
  },
  {
    id: "math-trig-003",
    subject: "Mathematics",
    chapter: "Introduction to Trigonometry",
    concept: "Trigonometric Identities",
    difficulty: "easy",
    questionType: "mcq",
    marks: 1,
    question: "Which of the following is a correct trigonometric identity?",
    options: [
      "sin²A – cos²A = 1",
      "sin²A + cos²A = 1",
      "tan²A + 1 = cos²A",
      "sec²A – tan²A = 0",
    ],
    correctAnswer: "sin²A + cos²A = 1",
    explanation: "sin²A + cos²A = 1 is the fundamental Pythagorean identity. The others are incorrect: sec²A – tan²A = 1 (not 0), and tan²A + 1 = sec²A (not cos²A).",
    cognitiveLevel: "remember",
  },
  {
    id: "math-trig-004",
    subject: "Mathematics",
    chapter: "Introduction to Trigonometry",
    concept: "Complementary Angles",
    difficulty: "medium",
    questionType: "mcq",
    marks: 1,
    question: "The value of tan 45° is:",
    options: ["0", "1", "√3", "1/√3"],
    correctAnswer: "1",
    explanation: "tan 45° = sin 45°/cos 45° = (1/√2)/(1/√2) = 1. In a 45-45-90 triangle, the two legs are equal, so opposite = adjacent.",
    cognitiveLevel: "remember",
  },
];

// ---------------------------------------------------------------------------
// Circles
// ---------------------------------------------------------------------------
export const circles: Question[] = [
  {
    id: "math-circ-001",
    subject: "Mathematics",
    chapter: "Circles",
    concept: "Tangent to a Circle",
    difficulty: "easy",
    questionType: "mcq",
    marks: 1,
    question: "The number of tangents that can be drawn to a circle from an external point is:",
    options: ["1", "2", "3", "Infinite"],
    correctAnswer: "2",
    explanation: "Exactly two tangents can be drawn from an external point to a circle, and they are equal in length.",
    cognitiveLevel: "remember",
  },
  {
    id: "math-circ-002",
    subject: "Mathematics",
    chapter: "Circles",
    concept: "Tangent-Radius Property",
    difficulty: "easy",
    questionType: "mcq",
    marks: 1,
    question: "The tangent at any point of a circle is __________ to the radius through the point of contact.",
    options: ["Parallel", "Perpendicular", "Equal", "Bisecting"],
    correctAnswer: "Perpendicular",
    explanation: "The tangent to a circle at any point is perpendicular to the radius drawn to the point of contact. This means angle between radius and tangent = 90°.",
    cognitiveLevel: "remember",
  },
  {
    id: "math-circ-003",
    subject: "Mathematics",
    chapter: "Circles",
    concept: "Length of Tangent",
    difficulty: "medium",
    questionType: "mcq",
    marks: 1,
    question: "From an external point P, the length of the tangent to a circle with centre O and radius 5 cm is 12 cm. Then OP =",
    options: ["13 cm", "17 cm", "7 cm", "10 cm"],
    correctAnswer: "13 cm",
    explanation: "The radius OT ⊥ PT (tangent). In right triangle OTP: OP² = OT² + PT² = 5² + 12² = 25 + 144 = 169. So OP = 13 cm.",
    cognitiveLevel: "apply",
  },
];

// ---------------------------------------------------------------------------
// Statistics
// ---------------------------------------------------------------------------
export const statistics: Question[] = [
  {
    id: "math-stat-001",
    subject: "Mathematics",
    chapter: "Statistics",
    concept: "Mean",
    difficulty: "easy",
    questionType: "mcq",
    marks: 1,
    question: "The mean of 3, 5, 7, 9, 11 is:",
    options: ["7", "9", "5", "6"],
    correctAnswer: "7",
    explanation: "Mean = Sum/Count = (3+5+7+9+11)/5 = 35/5 = 7.",
    cognitiveLevel: "apply",
  },
  {
    id: "math-stat-002",
    subject: "Mathematics",
    chapter: "Statistics",
    concept: "Mode",
    difficulty: "easy",
    questionType: "mcq",
    marks: 1,
    question: "The mode of the data: 2, 3, 4, 5, 4, 3, 4, 6, 4, 2 is:",
    options: ["3", "4", "2", "5"],
    correctAnswer: "4",
    explanation: "Mode is the value that appears most frequently. 4 appears 4 times, which is more than any other value.",
    cognitiveLevel: "apply",
  },
  {
    id: "math-stat-003",
    subject: "Mathematics",
    chapter: "Statistics",
    concept: "Median",
    difficulty: "medium",
    questionType: "mcq",
    marks: 1,
    question: "The median of data 12, 15, 18, 22, 25 is:",
    options: ["18", "15", "22", "19"],
    correctAnswer: "18",
    explanation: "Data is already arranged in ascending order. n = 5 (odd). Median = ((n+1)/2)th term = 3rd term = 18.",
    cognitiveLevel: "apply",
  },
];

// ---------------------------------------------------------------------------
// Probability
// ---------------------------------------------------------------------------
export const probability: Question[] = [
  {
    id: "math-prob-001",
    subject: "Mathematics",
    chapter: "Probability",
    concept: "Basic Probability",
    difficulty: "easy",
    questionType: "mcq",
    marks: 1,
    question: "A die is thrown once. The probability of getting a number greater than 4 is:",
    options: ["1/2", "1/3", "1/6", "2/3"],
    correctAnswer: "1/3",
    explanation: "Numbers greater than 4 on a die: {5, 6} → 2 favourable outcomes. Total outcomes = 6. P = 2/6 = 1/3.",
    cognitiveLevel: "apply",
  },
  {
    id: "math-prob-002",
    subject: "Mathematics",
    chapter: "Probability",
    concept: "Complementary Events",
    difficulty: "easy",
    questionType: "mcq",
    marks: 1,
    question: "If P(E) = 0.7, then P(Ē) =",
    options: ["0.3", "0.7", "1.7", "0"],
    correctAnswer: "0.3",
    explanation: "P(E) + P(Ē) = 1 (complementary events). So P(Ē) = 1 – P(E) = 1 – 0.7 = 0.3.",
    cognitiveLevel: "remember",
  },
  {
    id: "math-prob-003",
    subject: "Mathematics",
    chapter: "Probability",
    concept: "Cards",
    difficulty: "medium",
    questionType: "mcq",
    marks: 1,
    question: "A card is drawn at random from a well-shuffled pack of 52 cards. The probability of getting a red queen is:",
    options: ["1/26", "1/52", "2/52", "1/13"],
    correctAnswer: "1/26",
    explanation: "There are 2 red queens (Queen of Hearts and Queen of Diamonds) in 52 cards. P = 2/52 = 1/26.",
    cognitiveLevel: "apply",
  },
];

// ---------------------------------------------------------------------------
// Surface Areas and Volumes
// ---------------------------------------------------------------------------
export const surfaceAreasVolumes: Question[] = [
  {
    id: "math-sav-001",
    subject: "Mathematics",
    chapter: "Surface Areas and Volumes",
    concept: "Cylinder",
    difficulty: "easy",
    questionType: "mcq",
    marks: 1,
    question: "The curved surface area of a cylinder with radius 7 cm and height 10 cm is (π = 22/7):",
    options: ["440 cm²", "220 cm²", "880 cm²", "154 cm²"],
    correctAnswer: "440 cm²",
    explanation: "CSA of cylinder = 2πrh = 2 × (22/7) × 7 × 10 = 2 × 22 × 10 = 440 cm².",
    cognitiveLevel: "apply",
  },
  {
    id: "math-sav-002",
    subject: "Mathematics",
    chapter: "Surface Areas and Volumes",
    concept: "Sphere",
    difficulty: "medium",
    questionType: "mcq",
    marks: 1,
    question: "The volume of a sphere with radius 3 cm is (π = 22/7):",
    options: ["113.14 cm³", "36π cm³", "12π cm³", "4π cm³"],
    correctAnswer: "113.14 cm³",
    explanation: "V = (4/3)πr³ = (4/3) × (22/7) × 3³ = (4/3) × (22/7) × 27 = 4 × 22 × 27/21 = 2376/21 ≈ 113.14 cm³.",
    cognitiveLevel: "apply",
  },
];

// ---------------------------------------------------------------------------
// All Maths chapters index
// ---------------------------------------------------------------------------
export const mathsChapters = [
  { id: "real-numbers", name: "Real Numbers", questions: realNumbers },
  { id: "polynomials", name: "Polynomials", questions: polynomials },
  { id: "arithmetic-progressions", name: "Arithmetic Progressions", questions: arithmeticProgressions },
  { id: "quadratic-equations", name: "Quadratic Equations", questions: quadraticEquations },
  { id: "triangles", name: "Triangles", questions: triangles },
  { id: "coordinate-geometry", name: "Coordinate Geometry", questions: coordinateGeometry },
  { id: "trigonometry", name: "Introduction to Trigonometry", questions: trigonometry },
  { id: "circles", name: "Circles", questions: circles },
  { id: "surface-areas-volumes", name: "Surface Areas and Volumes", questions: surfaceAreasVolumes },
  { id: "statistics", name: "Statistics", questions: statistics },
  { id: "probability", name: "Probability", questions: probability },
];
