/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TargetsRouteImport } from './routes/targets'
import { Route as SeedRouteImport } from './routes/seed'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects.index'
import { Route as SubjectsSubjectIdRouteImport } from './routes/subjects.$subjectId'
import { Route as AdminImportRouteImport } from './routes/admin.import'

const TargetsRoute = TargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedRoute = SeedRouteImport.update({
  id: '/seed',
  path: '/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdRoute = SubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/admin/import',
  path: '/admin/import',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/focus': typeof FocusRoute
  '/planner': typeof PlannerRoute
  '/seed': typeof SeedRoute
  '/targets': typeof TargetsRoute
  '/admin/import': typeof AdminImportRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/subjects/': typeof SubjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/focus': typeof FocusRoute
  '/planner': typeof PlannerRoute
  '/seed': typeof SeedRoute
  '/targets': typeof TargetsRoute
  '/admin/import': typeof AdminImportRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/subjects': typeof SubjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/focus': typeof FocusRoute
  '/planner': typeof PlannerRoute
  '/seed': typeof SeedRoute
  '/targets': typeof TargetsRoute
  '/admin/import': typeof AdminImportRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/subjects/': typeof SubjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/focus'
    | '/planner'
    | '/seed'
    | '/targets'
    | '/admin/import'
    | '/subjects/$subjectId'
    | '/subjects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/focus'
    | '/planner'
    | '/seed'
    | '/targets'
    | '/admin/import'
    | '/subjects/$subjectId'
    | '/subjects'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/focus'
    | '/planner'
    | '/seed'
    | '/targets'
    | '/admin/import'
    | '/subjects/$subjectId'
    | '/subjects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  FocusRoute: typeof FocusRoute
  PlannerRoute: typeof PlannerRoute
  SeedRoute: typeof SeedRoute
  TargetsRoute: typeof TargetsRoute
  AdminImportRoute: typeof AdminImportRoute
  SubjectsSubjectIdRoute: typeof SubjectsSubjectIdRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/targets': {
      id: '/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof TargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seed': {
      id: '/seed'
      path: '/seed'
      fullPath: '/seed'
      preLoaderRoute: typeof SeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId': {
      id: '/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof SubjectsSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  FocusRoute: FocusRoute,
  PlannerRoute: PlannerRoute,
  SeedRoute: SeedRoute,
  TargetsRoute: TargetsRoute,
  AdminImportRoute: AdminImportRoute,
  SubjectsSubjectIdRoute: SubjectsSubjectIdRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
